### ISSUE TITLE
No Display or change of time/date settings

### ISSUE THREAD

**Issue by git-marc** [microbit-makecode-packages/DS1307#1]
Issue:
No Display or change of time/date settings with makecode.microbit.org + "Neopixel" library

I can not see any of my time/date inputs changing the default settings
- using the microbic editor (https://makecode.microbit.org/#editor)
- without being connected with the DS1307 module
(- having the "Neopixel" library loaded)

May you please let me know what I can do do see changes with microbic's online simulator (+ the "Neopixel" library loaded)?

I look forward to hearing from you,
best regards

_________________________________________________________
**MY CODES (some of my tries)**

**_.............................................................
TRY 1_**
_input.onButtonPressed(Button.A, function () {
    DS1307.setYear(2018)
    basic.showString("" + DS1307.getYear())
})
DS1307.start()

**_.............................................................
TRY 2_**
input.onButtonPressed(Button.A, function () {
    DS1307.setYear(2018)
    basic.pause(100)
    basic.showString("" + DS1307.getYear())
})
DS1307.start()
basic.pause(100)

_________________________________________________________
**MY SYSTEM**
macOS: MOJAVE ( 10.14.1)
Browser: Safari (12.0.1), Firefox(63.0.3)
https://makecode.microbit.org/#editor

[HEX_FILES.zip](https://github.com/makecode-extensions/DS1307/files/2662112/HEX_FILES.zip)

**Comment by shaoziyang** [comment]
Can you provide more descriptions? How is the system connected? What is the performance of the problem?

**Comment by git-marc** [comment]
Please accept my apologies for my late reply:

I tried to use the MicroBit online Simulation ...
_(https://makecode.microbit.org/#editor)_
- whilst no device is connected (No MicroBit, No DS1307 module)
- with the "DS1307" library installed 

**_______________________________________________ 
Output**

- displayed via simulated LED matrix on microBit:  "2000" 
_(I assume that this is the default output)_

**_______________________________________________
desired/expected Output**

- displayed via LED matrix on microBit:  "2018" 

same default result for all other values that i tried before
(such as Second, Minute, Hour, Weekday, Day, Month, Year, DateTime)

![overview](https://user-images.githubusercontent.com/1135735/50009992-a14c5600-ffb8-11e8-8b7d-564e56bdf784.jpg)

**Comment by shaoziyang** [comment]
I have make a deep test again, and my DS1307 module is work fine with your code. There are maybe something wrong with your DS1307, can you try another DS1307 module?

**Comment by git-marc** [comment]
I never tested my Code Samples with a DS1307 module connected to my MacBookPro assuming that the DS1307 library allows for a preview though. So I actually do need to have a DS1307 module connected for testing?

**Comment by shaoziyang** [comment]
Yes, a DS1307 module is need for test. Because hardware I2C is not support in makecode simulator .

**Comment by git-marc** [comment]
Thank You for the information!
